import assert from 'node:assert/strict';
import { LIBRARY_KEY, cleanProject, copyProject, newProject, readLibrary, writeLibrary } from '../src/projects/projectStore';
const values = new Map<string,string>();
const storage = {getItem:(key:string)=>values.get(key) ?? null,setItem:(key:string,value:string)=>{values.set(key,value);}};
const original = newProject('原项目').project;
const canvas = original.canvases[0];
canvas.nodes = [
  {id:'text-original',type:'canvas-card',position:{x:3,y:7},data:{kind:'text',text:'保留原剧本'}},
  {id:'image-original',type:'canvas-card',position:{x:300,y:7},data:{kind:'image',assetId:'shared-media',assetUrl:'blob:runtime',imageGeneration:{referenceIds:['text-original']} as never}},
];
canvas.edges=[{id:'edge-original',source:'text-original',target:'image-original',data:{relation:'sequence'}}];
canvas.viewport={x:125,y:-72,zoom:0.65};
values.set('mjh.project.v2',JSON.stringify(original));
const oldRecord = values.get('mjh.project.v2');
const migrated = readLibrary(storage,()=>original);
assert.equal(migrated.projects.length,1);
assert.equal(values.get('mjh.project.v2'),oldRecord);
assert.deepEqual(migrated.projects[0].project.canvases[0].viewport,canvas.viewport);
assert.equal(migrated.projects[0].project.canvases[0].nodes[1].data.assetId,'shared-media');
assert.equal(migrated.projects[0].project.canvases[0].nodes[1].data.assetUrl,undefined);
const reread=readLibrary(storage,()=>{throw new Error('must not migrate twice');});
assert.equal(reread.projects[0].id,migrated.projects[0].id);
console.log('✓ legacy migration preserves original storage, viewport and media; runs once');
const fresh=newProject('新项目');
assert.equal(fresh.project.canvases[0].nodes.length,0);
assert.notEqual(fresh.id,migrated.projects[0].id);
console.log('✓ new projects are independent and empty');
const copy=copyProject(migrated.projects[0]);
assert.notEqual(copy.id,migrated.projects[0].id);
assert.notEqual(copy.project.activeCanvasId,canvas.id);
assert.equal(copy.project.activeCanvasId,copy.project.canvases[0].id);
const copied=copy.project.canvases[0];
assert.notEqual(copied.nodes[0].id,'text-original');
assert.equal(copied.edges![0].source,copied.nodes[0].id);
assert.equal(copied.edges![0].target,copied.nodes[1].id);
assert.equal(copied.edges![0].data?.relation,'sequence');
assert.equal(copied.nodes[1].data.imageGeneration?.referenceIds[0],copied.nodes[0].id);
assert.equal(copied.nodes[1].data.assetId,'shared-media');
copied.nodes[0].data.text='独立修改';
assert.equal(migrated.projects[0].project.canvases[0].nodes[0].data.text,'保留原剧本');
console.log('✓ copies remap nodes, canvases, edges and generation references without changing original');
const trashed={...copy,trashedAt:new Date().toISOString()};
writeLibrary(storage,{...migrated,projects:[...migrated.projects,trashed]});
const restored=readLibrary(storage,()=>original).projects[1];
assert.equal(restored.trashedAt,trashed.trashedAt);
assert.equal(restored.project.canvases[0].nodes[0].data.text,'独立修改');
console.log('✓ recycle-bin entries retain all project content across reload');
values.set(LIBRARY_KEY,'{broken json');
assert.throws(()=>readLibrary(storage,()=>original));
assert.equal(values.get(LIBRARY_KEY),'{broken json');
assert.throws(()=>writeLibrary({getItem:()=>null,setItem:()=>{throw new Error('quota');}},migrated));
assert.equal(cleanProject(original).canvases[0].nodes[1].data.assetUrl,undefined);
assert.equal(original.canvases[0].nodes[1].data.assetUrl,'blob:runtime');
console.log('✓ corruption and quota errors never overwrite originals; serialization is non-mutating');
